- swmmio/utils/dataframes.py
> cast lookup ID to string in get_link_coords()

- setup.py
- swmmio/swmmio.py
- swmmio/tests/test_dataframes.py
> Slash obsolete and out of scopers in swmmio.py, added tests

- requirements.txt
- setup.py
- swmmio/__init__.py
> explicitly set dependencies versions for py2.7 compatibility

- .travis.yml
- appveyor.yml
- requirements.txt
- setup.py
- swmmio/__init__.py
- swmmio/core.py
- swmmio/defs/section_headers.json
- swmmio/defs/sectionheaders.py
- swmmio/tests/data/model_full_features_network_xy.inp
- swmmio/tests/test_dataframes.py
- swmmio/tests/test_model_elements.py
- swmmio/utils/dataframes.py
- swmmio/utils/functions.py
Requires Networkx (used to be optional) and updates to latest version. Also updates Pillow to patch a security vulnerability. Appveyor CI configured to auto release tagged releases now to PyPi.
Closes #72 
Closes #71 
Closes #74
> Update networkx, autorelease to PyPi

- MANIFEST.in
> add yml files to dist

- swmmio/tests/test_version_control.py
> use tempdir contexts in unit vc tests

- swmmio/elements.py
- swmmio/tests/test_dataframes.py
- swmmio/tests/test_model_elements.py
- swmmio/tests/test_version_control.py
- swmmio/utils/modify_model.py
- `m.inp.subcatchments.dataframe` will return empty dataframe if no subcatchments exist in model
- fixed bug causing `m.inp.save()` to fail after changes were made to the `m.inp` object
Closes #90 
Closes #87
> fix issue with empty subcatchments and changing inp objects

- .travis.yml
- docs/README.md
- docs/conf.py
- docs/index.rst
- docs/inp.rst
- docs/modules.rst
- docs/swmmio.rst
- docs/version_control.rst
- requirements.txt
- swmmio/__init__.py
- swmmio/core.py
- swmmio/elements.py
- swmmio/examples.py
- swmmio/tests/data/__init__.py
- swmmio/version_control/__init__.py
- swmmio/version_control/inp.py
- Reformat and expand a lot of docstrings so that autodoc works better
- cast ModelSection index to string sooner
- include Python 3.8 in travis unit tests
Closes #100
> Improve docstrings, ModelSection index cast

- swmmio/core.py
> Fixing setter references

- requirements.txt
- setup.py
- swmmio/core.py
- swmmio/graphics/swmm_graphics.py
- swmmio/tests/test_graphics.py
- swmmio/utils/spatial.py
- Update the `pyproj` dependency version and update the coordinate transformation logic to use the new [Transformer](https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1) object.  
- update the `geojson` version to eliminate a depreciation warning. 
Closes #118
> update pyproj version and transform logic

- swmmio/utils/modify_model.py
> Fix to overwrite options section 

- swmmio/tests/data/owa-rpt-example.rpt
- swmmio/tests/test_dataframes.py
- swmmio/utils/dataframes.py
Handles edge case in RPT files in Node Flooding Summary when no nodes were flooded during the simulation.
Closes #108
> handle rpt file edge case when no nodes are flooded

- swmmio/graphics/swmm_graphics.py
- swmmio/reporting/basemaps/mapbox_base.html
> update mapbox version, add optional basemap argument

- appveyor.yml
- setup.py
> add pyproj>=3.0.0 to setup.py

- swmmio/core.py
> add DWF to inp module

- swmmio/tests/test_dataframes.py
- swmmio/utils/text.py
This simplifies some logic in `swmmio/utils/text.py` and adds a unit test to ensure the UnboundLocalError is not raised, as observed [here](https://ci.appveyor.com/project/aerispaha/swmmio/builds/45739396#L645).
Closes #141
> Fix bug causing UnboundLocalError: local variable 'h' in text.py

- .github/workflows/python-app.yml
- appveyor.yml
- swmmio/core.py
- swmmio/elements.py
> fix doctests in core.py

- docs/conf.py
- swmmio/__init__.py
> fix version number in docs/config.py

- swmmio/core.py
- swmmio/defs/section_headers.yml
This PR includes a couple minor tweaks following #186 from @BuczynskiRafal
> Code simplification in Model.conduits

- .mailmap
- AUTHORS
- swmmio/core.py
- swmmio/defs/inp_sections.yml
This addresses the outstanding comments from PR #193 and updates the AUTHORS file. 
Closes #190
> Address outstanding comments in PR193, update AUTHORS

- README.md
- swmmio/__init__.py
- swmmio/graphics/drawing.py
- swmmio/graphics/swmm_graphics.py
- swmmio/tests/test_graphics.py
> include all links in draw_model, optionally return html in create_map 

- docs/conf.py
- requirements.txt
- setup.py
Upgrades and loosens the pyshp dependency in requiements.txt and setup.py, respectively. 
Closes #234
> upgrade pyshp dependency
